#!/bin/bash

source "$CONFIG_DIR/colors.sh"

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=40 margin=0 blur_radius=30 sticky=on color=$BAR_COLOR

##### Defaults #####
default=(
  padding_left=4
  padding_right=4
  icon.font="$FONT_FACE:SemiBold:14.0"
  label.font="$FONT_FACE:SemiBold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.drawing=off
  background.corner_radius=0
  background.height=24
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=6
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

##### Right Side Items #####
source $ITEM_DIR/gpu.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

sketchybar --add bracket right_group gpu ram cpu volume battery \
  --set right_group background.color=$ITEM_BG_COLOR background.height=24 background.corner_radius=6 \
  background.padding_left=4 background.padding_right=4

source $ITEM_DIR/calendar.sh

##### Force all scripts to run the first time #####
sketchybar --update
