#!/bin/bash

source "$CONFIG_DIR/colors.sh"

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=40 margin=0 blur_radius=30 sticky=on color=$BAR_COLOR

##### Defaults #####
default=(
  padding_left=4
  padding_right=4
  icon.font="$FONT_FACE:Regular:13.0"
  label.font="$FONT_FACE:Regular:13.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.drawing=off
  background.corner_radius=0
  background.height=24
  icon.padding_left=6
  icon.padding_right=3
  label.padding_left=3
  label.padding_right=6
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

##### Right Side Items #####
sketchybar --add item sep_gpu right \
  --set sep_gpu label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/gpu.sh

sketchybar --add item sep_ram right \
  --set sep_ram label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/ram.sh

sketchybar --add item sep_cpu right \
  --set sep_cpu label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/cpu.sh

sketchybar --add item sep_vol right \
  --set sep_vol label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/volume.sh

sketchybar --add item sep_bat right \
  --set sep_bat label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/battery.sh

sketchybar --add item sep_cal right \
  --set sep_cal label="|" label.color=0xff666666 background.drawing=off \
  padding_left=0 padding_right=0

source $ITEM_DIR/calendar.sh

##### Force all scripts to run the first time #####
sketchybar --update
